---
- name: set subject alt name for Google Chrome 58 or more
  blockinfile:
    path: /etc/pki/tls/openssl.cnf
    block: |
      subjectAltName=DNS:*.{{ roles_common_domain_name }}
    insertafter: \[\susr_cert\s\]

- name: certificate authority for identify server
  command: openssl ca -batch -in /etc/pki/tls/certs/servercert.csr -out /etc/pki/tls/certs/servercert.pem -days 36500
  args:
    creates: /etc/pki/tls/certs/servercert.pem
