---
- name: copy into install directory
  copy:
    src: /etc/pki/CA/cacert.pem
    dest: /etc/pki/ca-trust/source/anchors/cacert.pem
    remote_src: yes

- name: download certificate authority for Amazon RDS
  uri:
    url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    dest: /etc/pki/ca-trust/source/anchors/rds-combined-ca-bundle.pem
    creates: /etc/pki/ca-trust/source/anchors/rds-combined-ca-bundle.pem

- name: enable update-ca-trust function
  command: update-ca-trust enable

- name: install CA cert
  command: update-ca-trust extract
